# Generated by Django 3.2 on 2023-01-26 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=80)),
                ('receiver', models.CharField(max_length=250)),
                ('shared_receiver', models.CharField(blank=True, max_length=250)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('joint_file', models.FileField(blank=True, upload_to='emails/join_files/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('email_type', models.CharField(choices=[('SIGNUP', 'Signup'), ('SIGNIN', 'Signin'), ('PASSRESREQ', 'Password reset request')], default='SIGNUP', max_length=20)),
            ],
        ),
    ]
